# Generated by Django 4.2.10 on 2024-02-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
