# Generated by Django 4.2.10 on 2024-02-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_college_phone_teamcaptain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamcaptain',
            old_name='name',
            new_name='captain_name',
        ),
    ]
