# Generated by Django 4.2.10 on 2024-02-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_name_teamcaptain_captain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='sport_amount',
            field=models.DecimalField(decimal_places=2, default=4500, max_digits=10),
            preserve_default=False,
        ),
    ]
