# Generated by Django 4.2.10 on 2024-02-26 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sport_sport_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='facebook_profile',
            new_name='instagram_profile',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='twitter_profile',
            new_name='mail_profile',
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a', models.CharField(max_length=50)),
                ('team_b', models.CharField(max_length=50)),
                ('score_a', models.CharField(max_length=10)),
                ('score_b', models.CharField(max_length=10)),
                ('result', models.CharField(max_length=100)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sport')),
            ],
        ),
    ]
