# Generated by Django 4.2.10 on 2024-02-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_facebook_profile_teammember_instagram_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='mail_profile',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
