# Generated by Django 4.2.10 on 2024-02-27 05:29

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_teammember_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to=main.models.team_member_image_upload),
        ),
    ]
