# Generated by Django 4.2.10 on 2024-03-05 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_teammember_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
